version: "3.9"
services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: home_sales_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
